name        : gvfs
version     : 1.26.1
release     : 13
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gvfs/1.26/gvfs-1.26.1.tar.xz : 1c6e8ee47486646102d0bc8f4062362908968c0a24d68a7c5e57a103ab0b6380
license     :
    - GPLv2+
summary     : Userspace virtual filesystem
builddeps   :
    - pkgconfig(udisks2)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libplist)
    - pkgconfig(fuse)
    - pkgconfig(libmtp)
    - pkgconfig(libbluray)
    - pkgconfig(libgphoto2)
    - pkgconfig(smbclient)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(avahi-glib)
    - pkgconfig(gcr-base-3)
    - pkgconfig(libgdata)
    - pkgconfig(goa-1.0)
    - cifs-utils-devel
    - libgcrypt-devel
description : |
    The Gvfs package is a userspace virtual filesystem designed to work with the I/O abstractions of GLib's GIO library.
setup      : |
    %configure --enable-gphoto2 \
               --disable-documentation \
               --enable-afc \
               --enable-cdda \
               --enable-libsystemd-login \
               --enable-google
build      : |
    %make
install    : |
    %make_install
