name       : gvfs
version    : 1.28.2
release    : 15
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gvfs/1.28/gvfs-1.28.2.tar.xz : bc6af45cff7e7e8d33c3a4be1d27e479f10f80105a6f2d1fae75c5c0d40636d9
license    :
    - GPLv2+
summary    : Userspace virtual filesystem
builddeps  :
    - pkgconfig(udisks2)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libplist)
    - pkgconfig(fuse)
    - pkgconfig(libmtp)
    - pkgconfig(libbluray)
    - pkgconfig(libgphoto2)
    - pkgconfig(smbclient)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(avahi-glib)
    - pkgconfig(gcr-base-3)
    - pkgconfig(libgdata)
    - pkgconfig(goa-1.0)
    - cifs-utils-devel
    - libgcrypt-devel
description: |
    The Gvfs package is a userspace virtual filesystem designed to work with the I/O abstractions of GLib's GIO library.
setup      : |
    %configure --enable-gphoto2 \
               --disable-documentation \
               --enable-afc \
               --enable-cdda \
               --enable-libsystemd-login \
               --enable-google
build      : |
    %make
install    : |
    %make_install
