name       : gvfs
version    : '1.42'
release    : 46
source     :
    - https://download.gnome.org/sources/gvfs/1.42/gvfs-1.42.0.tar.xz : d0958d9ceefb54bb8ddda74ef51e10fe03dff93f74634784bd309ea434066cf1
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    :
    - goa : GNOME Online Accounts support in gvfs
    - Userspace virtual filesystem
description: |
    The Gvfs package is a userspace virtual filesystem designed to work with the I/O abstractions of GLib's GIO library.
patterns   :
    - goa :
        - /usr/lib64/gvfs/gvfsd-google
        - /usr/lib/systemd/user/gvfs-goa-volume-monitor.service
        - /usr/lib64/gvfs/gvfs-goa-volume-monitor
        - /usr/share/dbus-1/services/org.gtk.vfs.GoaVolumeMonitor.service
        - /usr/share/gvfs/remote-volume-monitors/goa.monitor
        - /usr/share/gvfs/mounts/google.mount
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(fuse)
    - pkgconfig(gcr-base-3)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gudev-1.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libbluray)
    - pkgconfig(libcap)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libgdata)
    - pkgconfig(libgphoto2)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnfs)
    - pkgconfig(libplist)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(smbclient)
    - pkgconfig(udisks2)
    - cifs-utils-devel
    - libgcrypt-devel
    - openssh
rundeps    :
    - goa : gvfs
    - lsof
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-fuse-Adapt-gvfsd-fuse-to-use-fuse-3.x.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # support keyfile backend in gvfs
    install -m 00644 $pkgfiles/org.gtk.vfs.file-operations.keyrules $installdir/usr/share/polkit-1/rules.d/.
