name       : gvfs
version    : 1.30.3
release    : 18
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gvfs/1.30/gvfs-1.30.3.tar.xz : b824a29489cae7f39e1a0fc0d154ac7b7bf43d8edd98ba83ffcad2f766d0f175
license    : GPL-2.0
component  : desktop.gnome.core
summary    :
    - goa : GNOME Online Accounts support in gvfs
    - Userspace virtual filesystem
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(udisks2)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libplist)
    - pkgconfig(fuse)
    - pkgconfig(libcap)
    - pkgconfig(libmtp)
    - pkgconfig(libbluray)
    - pkgconfig(libgphoto2)
    - pkgconfig(smbclient)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(avahi-glib)
    - pkgconfig(gcr-base-3)
    - pkgconfig(libgdata)
    - pkgconfig(goa-1.0)
    - cifs-utils-devel
    - libgcrypt-devel
patterns   :
    - goa :
        - /usr/lib64/gvfs/gvfsd-google
        - /usr/lib/systemd/user/gvfs-goa-volume-monitor.service
        - /usr/lib64/gvfs/gvfs-goa-volume-monitor
        - /usr/share/dbus-1/services/org.gtk.vfs.GoaVolumeMonitor.service
        - /usr/share/gvfs/remote-volume-monitors/goa.monitor
        - /usr/share/gvfs/mounts/google.mount
rundeps    :
    - goa : gvfs
description: |
    The Gvfs package is a userspace virtual filesystem designed to work with the I/O abstractions of GLib's GIO library.
setup      : |
    %configure --enable-gphoto2 \
               --disable-documentation \
               --enable-afc \
               --enable-cdda \
               --enable-libsystemd-login \
               --enable-google
build      : |
    %make
install    : |
    %make_install
