name       : gvfs
version    : 1.36.2
release    : 41
source     :
    - https://download.gnome.org/sources/gvfs/1.36/gvfs-1.36.2.tar.xz : c4e279a33dd9cd208135e8bfc4788ceaf264c61a24a85255f6696a934a0101f7
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    :
    - goa : GNOME Online Accounts support in gvfs
    - Userspace virtual filesystem
description: |
    The Gvfs package is a userspace virtual filesystem designed to work with the I/O abstractions of GLib's GIO library.
patterns   :
    - goa :
        - /usr/lib64/gvfs/gvfsd-google
        - /usr/lib/systemd/user/gvfs-goa-volume-monitor.service
        - /usr/lib64/gvfs/gvfs-goa-volume-monitor
        - /usr/share/dbus-1/services/org.gtk.vfs.GoaVolumeMonitor.service
        - /usr/share/gvfs/remote-volume-monitors/goa.monitor
        - /usr/share/gvfs/mounts/google.mount
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(fuse)
    - pkgconfig(gcr-base-3)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gudev-1.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libbluray)
    - pkgconfig(libcap)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libgdata)
    - pkgconfig(libgphoto2)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnfs)
    - pkgconfig(libplist)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(smbclient)
    - pkgconfig(udisks2)
    - cifs-utils-devel
    - libgcrypt-devel
    - openssh
rundeps    :
    - goa : gvfs
    - lsof
setup      : |
    %meson_configure -Ddeprecated_programs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    # support keyfile backend in gvfs
    install -m 00644 $pkgfiles/org.gtk.vfs.file-operations.keyrules $installdir/usr/share/polkit-1/rules.d/.
