name       : gvfs
version    : 1.50.0
release    : 73
source     :
    - https://download.gnome.org/sources/gvfs/1.50/gvfs-1.50.0.tar.xz : cbc2f564d2e9f00c760673f42d6803bce3e081ab7ffb4456deffffba9339b4dd
homepage   : https://wiki.gnome.org/Projects/gvfs
license    : GPL-2.0-only
component  :
    - desktop.gnome.core
    - goa : desktop.gnome.core
summary    :
    - goa : GNOME Online Accounts support in gvfs
    - Userspace virtual filesystem
description: |
    The Gvfs package is a userspace virtual filesystem designed to work with the I/O abstractions of GLib's GIO library.
patterns   :
    - goa :
        - /usr/lib64/gvfs/gvfsd-google
        - /usr/lib/systemd/user/gvfs-goa-volume-monitor.service
        - /usr/lib64/gvfs/gvfs-goa-volume-monitor
        - /usr/share/dbus-1/services/org.gtk.vfs.GoaVolumeMonitor.service
        - /usr/share/gvfs/remote-volume-monitors/goa.monitor
        - /usr/share/gvfs/mounts/google.mount
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(fuse3)
    - pkgconfig(gcr-base-3)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gudev-1.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libbluray)
    - pkgconfig(libcap)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libgdata)
    - pkgconfig(libgphoto2)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libnfs)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(smbclient)
    - pkgconfig(udisks2)
    - cifs-utils-devel
    - libgcrypt-devel
    - openssh
rundeps    :
    - goa : gvfs
    - lsof
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-ProxyVolumeMonitor-Don-t-leak-a-GVfsDBusDaemo.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # support keyfile backend in gvfs
    install -Dm00644 $pkgfiles/org.gtk.vfs.file-operations.keyrules -t $installdir/usr/share/polkit-1/rules.d/
